library verilog;
use verilog.vl_types.all;
entity p405s_fileAddrGen is
    port(
        PCL_LpEqAp      : out    vl_logic;
        PCL_LpEqBp      : out    vl_logic;
        PCL_LpEqSp      : out    vl_logic;
        PCL_RpEqAp      : out    vl_logic;
        PCL_RpEqBp      : out    vl_logic;
        PCL_RpEqSp      : out    vl_logic;
        PCL_dcdApAddr   : out    vl_logic_vector(0 to 9);
        PCL_dcdBpAddr   : out    vl_logic_vector(0 to 9);
        PCL_dcdSpAddr   : out    vl_logic_vector(0 to 9);
        PCL_lwbLpAddr   : out    vl_logic_vector(0 to 4);
        PCL_wbRpAddr    : out    vl_logic_vector(0 to 4);
        exeApAddrL2     : out    vl_logic_vector(0 to 4);
        exeMorMRpEqdcdApAddr: out    vl_logic;
        exeMorMRpEqdcdBpAddr: out    vl_logic;
        exeMorMRpEqexeRpAddr: out    vl_logic;
        exeMorMRpEqlwbLpAddr: out    vl_logic;
        exeMorMRpEqwbLpAddr: out    vl_logic;
        exeRTeqRA       : out    vl_logic;
        exeRTeqRB       : out    vl_logic;
        exeRpEqdcdApAddr: out    vl_logic;
        exeRpEqdcdBpAddr: out    vl_logic;
        exeRpEqdcdSpAddr: out    vl_logic;
        exeRpEqlwbLpAddr: out    vl_logic;
        exeRpEqwbLpAddr : out    vl_logic;
        gprLpeqRp       : out    vl_logic;
        lwbLpEqdcdSpAddr: out    vl_logic;
        lwbLpEqexeApAddr: out    vl_logic;
        lwbLpEqexeBpAddr: out    vl_logic;
        lwbLpEqexeSpAddr: out    vl_logic;
        wbLpEqdcdApAddr : out    vl_logic;
        wbLpEqdcdBpAddr : out    vl_logic;
        wbLpEqdcdSpAddr : out    vl_logic;
        wbLpEqexeApAddr : out    vl_logic;
        wbLpEqexeBpAddr : out    vl_logic;
        wbLpEqexeSpAddr : out    vl_logic;
        APU_dcdUpdate   : in     vl_logic;
        CB              : in     vl_logic;
        DRCC            : in     vl_logic;
        ERC             : in     vl_logic;
        IFB_dcdFullL2   : in     vl_logic;
        LSSD_coreTestEn : in     vl_logic;
        PCL_exeMacEnL2  : in     vl_logic;
        PCL_exeMultEnL2 : in     vl_logic;
        c2Clk           : in     vl_logic;
        dcdPriOpL2      : in     vl_logic_vector(0 to 5);
        dcdRAL2         : in     vl_logic_vector(0 to 4);
        dcdRBL2         : in     vl_logic_vector(0 to 4);
        dcdRSRTL2       : in     vl_logic_vector(0 to 4);
        dcdSecOpL2      : in     vl_logic_vector(21 to 31);
        exe1FullL2      : in     vl_logic;
        exe2FullL2      : in     vl_logic;
        exeE1           : in     vl_logic;
        exeE2           : in     vl_logic;
        exeLpAddrE2     : in     vl_logic;
        exeLpMuxSel     : in     vl_logic;
        exeMacOrMultRpAddrE2: in     vl_logic;
        exeRpAddrE2     : in     vl_logic;
        exeRpAddrMuxSel : in     vl_logic;
        exeSpAddrE2     : in     vl_logic;
        exeStore        : in     vl_logic;
        gtErr           : in     vl_logic;
        lwbE1           : in     vl_logic;
        lwbFullL2       : in     vl_logic;
        plaRpMuxSel     : in     vl_logic;
        sPortSelInc     : in     vl_logic;
        storeRSE1       : in     vl_logic;
        storeRSE2       : in     vl_logic;
        wbE1            : in     vl_logic;
        wbFullL2        : in     vl_logic;
        wbLpAddrE1      : in     vl_logic;
        wbRAL2          : in     vl_logic_vector(0 to 4);
        wbRpAddrE2      : in     vl_logic;
        PCL_BpEqSp      : out    vl_logic;
        PCL_gprRdClk    : out    vl_logic
    );
end p405s_fileAddrGen;
